update date string to use short `timeZoneName`
changing to `timeZoneName: "short"` date string to fix the following error observed on Chrome browsers in iphone 6s:
```
RangeError: timeZoneName must be "short" or "long"
```